### PR TITLE
Separate heating and cooling plant loops for gshp

### PR DESCRIPTION
**Pull request by joseph-robertson**
Can then disaggregate heating and cooling pump energy.

### CODE REVIEW

**Comment by shorowit** [comment]
Git subtree pushing to OpenStudio-HPXML repo for regression testing.

**Comment by shorowit** [comment]
I'm unfortunately seeing large diffs for buildings with GSHPs.

**Comment by joseph-robertson** [comment]
Hmm, I saw good agreement for our default SFD home. Can you tell me the scenarios you are testing?

**Comment by shorowit** [comment]
You can see it with the models produced by the valid-hvac-ground-to-air-heat-pump.xml file.

You can find CI CSV results for [OpenStudio-HPXML master](https://circleci.com/gh/NREL/OpenStudio-HPXML/275#artifacts/containers/0) and [OpenStudio-HPXML gshp-updates](https://circleci.com/gh/NREL/OpenStudio-HPXML/280#artifacts/containers/0) that show the large difference.

**Pull request closed without merging**
